trigger:
- master

variables:
  bastion_location: 'uksouth'
  bastion_rg: 'rdo-uks-bastion-rg'
  bastion_sa: 'rdouksbastionsa'
  bastion_name: 'rdo-uks-bastion'
  service_connection: 'DCD-CFT-Sandbox'
  pubkeysecfile: 'azure_rsa.pub'
  privkeysecfile: 'azure_rsa'
  System.Debug: False
  

jobs:
- job: Build
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: steps/00_build.yml
  #- template: steps/01_azure_setup.yml
  #- template: steps/02_string_replacement.yml
  #- template: steps/03_terraform.yml
  #- template: steps/04_custom_extentions.yml
  - template: steps/05_Inspec_testing.yml
    parameters:
      azureSubscription: $(service_connection)
      bastion_rg: $(bastion_rg)
      bastion_location: $(bastion_location)
      bastion_sa: $(bastion_sa)
      bastion_name: $(bastion_name)
      bastion_priv_ip: $(bastion_priv_ip)
      bastion_pub_ip: $(bastion_pub_ip)

