trigger:
- master
- iaas-only

variables:
  terraformVersion: 0.12.25
  agentPool: Ubuntu-18.04

stages:
- stage: TestValidatePlan
  displayName: "Test, validate and plan terraform"

  jobs:

  - template: pipeline-templates/terraform-test.yaml
    parameters:
      agentPool: ${{ variables.agentPool }}
      terraformVersion: ${{ variables.terraformVersion }}
      tfstate_serviceConnection: dcd-cft-sandbox
      tfstate_rg: dcd-cft-sandbox-tfstate
      tfstate_location: uksouth
      tfstate_storage_account: tfstate531ff96dc0b42082
      component: sbox

  - template: pipeline-templates/terraform-plan.yaml
    parameters:
      agentPool: ${{ variables.agentPool }}
      terraformVersion: ${{ variables.terraformVersion }}
      deployment_serviceConnection: dcd-cft-sandbox
      component: sbox

  # jobs:
  # - job: Test
  #   pool:
  #     vmImage: ${{ variables.agentPool }}

  #   steps:

  #   - task: PublishPipelineArtifact@1
  #     displayName: 'Publish Artifact: drop'
  #     inputs:
  #       targetPath: $(System.DefaultWorkingDirectory)
  #       artifactName: drop