parameters:
  - name: bastionHosts
    type: object
    default: 

    - environment: sbox
      tfstate_serviceConnection: dcd-cft-sandbox
      tfstate_rg: dcd-cft-sandbox-tfstate
      tfstate_location: uksouth
      tfstate_storage_account: tfstateed302caf1c3ce90e

    # - environment: test
    #   tfstate_serviceConnection: dts-management-test
    #   tfstate_rg: dts-management-test-tfstate
    #   tfstate_location: uksouth
    #   tfstate_storage_account: tfstated7b54c7febbb5bde

    # - environment: nonprod
    #   tfstate_serviceConnection: dts-management-nonprod-intsvc
    #   tfstate_rg: dts-management-nonprod-intsvc-tfstate
    #   tfstate_location: uksouth
    #   tfstate_storage_account: tfstateb44eb47999719b6f

    # - environment: prod
    #   tfstate_serviceConnection: dts-management-prod-intsvc
    #   tfstate_rg: dts-management-prod-intsvc-tfstate
    #   tfstate_location: uksouth
    #   tfstate_storage_account: tfstate2b1afc1958670244

trigger:
- master
- iaas-only

pr:
- master

variables:
  terraformVersion: 0.12.25
  agentPool: ubuntu-18.04

stages:
  - ${{ each bastion in parameters.bastionHosts }}:

    - stage: ${{ bastion.environment }}
      dependsOn: ${{ bastion.dependent_stage }}

      jobs:
      - job: Test
        condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
        pool:
          vmImage: ${{ variables.agentPool }}

        steps:
        - template: pipeline-templates/terraform-test.yaml

        - template: pipeline-templates/terraform-execute.yaml
          parameters:
            ${{ insert }}: ${{ bastion }}
            terraformVersion: ${{ variables.terraformVersion }}
            deploy: false

      - job: Deploy
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        pool:
          vmImage: ${{ variables.agentPool }}

        steps:
        - template: pipeline-templates/terraform-execute.yaml
          parameters:
            ${{ insert }}: ${{ bastion }}
            terraformVersion: ${{ variables.terraformVersion }}
            deploy: true