stages:
  - stage: WindowsStage
    displayName: "Windows Pool Stage"
    pool:
      name: hmcts-sds-ptlsbox-windows
    jobs:
      - job: WindowsJob
        displayName: "Windows Heartbeat"
        steps:
          - script: echo "Hello from Windows CMD"
            displayName: "CMD Test"
          
          - task: PowerShell@2
            displayName: "PowerShell Test"
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Hello from Windows PowerShell"
                Write-Host "PowerShell Version: $($PSVersionTable.PSVersion)"

  - stage: LinuxStage
    displayName: "Linux Pool Stage"
    dependsOn: []
    pool:
      name: hmcts-sds-ptlsbox
    jobs:
      - job: LinuxJob
        displayName: "Linux Heartbeat"
        steps:
          - script: echo "Keeping pool warm"
            displayName: "Heartbeat"
