---
- name: Ansible Host
  hosts: 127.0.0.1
  connection: local
  gather_facts: true
  become: true
  #vars:
    #ssh_permit_root_login: True
    #ssh_kerberos_support: True
    #ssh_allow_users: '*@hmcts.net'
  roles:
    - dev-sec.os-hardening
    #- dev-sec.ssh-hardening
  tasks:
    - name: ansible create directory example
      file:
        path: /tmp/devops_directory
        state: directory